In [1]:
import numpy as np


In [2]:
# Creating arrays from python lists

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4, 5], dtype = 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
# nested lists result in multidimensional arrays

np.array([range(i, i+3) for i in [2, 4, 6]])
# The inner lists are treated as rows of the resulting 2d arrays

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating arrays from scratch

In [6]:
# create a length 10 integer array filled with zeros

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Create a 3*5 floating-point array filled with 1's

np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create a 3*5 array filled with 3.14

np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# Create an array filled with a linear sequence starting at 0, ending at 20, stepping by 2 (this is similar to the built-in-range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# createa 3*3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.71317035, 0.74021282, 0.32634638],
       [0.75889431, 0.76835917, 0.136113  ],
       [0.08058293, 0.75371474, 0.47395372]])

In [12]:
# create a 3*3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.62202758,  1.75265214,  0.78716744],
       [ 0.04724057,  0.4395836 , -0.352401  ],
       [ 1.33599414,  1.36822441,  0.52059996]])

In [13]:
# create a 3*3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3 ))

array([[4, 8, 4],
       [4, 2, 2],
       [4, 8, 7]])

In [14]:
# create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# numpy attributes

In [16]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size = 6) # One dimensional array
x2 = np.random.randint(10, size = (3, 4)) # Two dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # Three dimensional array

print("The no of dimensions for x1: ", x1.ndim)
print("The size of each dimension for x1: ", x1.shape)
print("The total size of the array x1: ", x1.size)

print("The no of dimensions for x2: ", x2.ndim)
print("The size of each dimension for x2: ", x2.shape)
print("The total size of the array x2: ", x2.size)

print("The no of dimensions for x3: ", x3.ndim)
print("The size of each dimension for x3: ", x3.shape)
print("The total size of the array x3: ", x3.size)

The no of dimensions for x1:  1
The size of each dimension for x1:  (6,)
The total size of the array x1:  6
The no of dimensions for x2:  2
The size of each dimension for x2:  (3, 4)
The total size of the array x2:  12
The no of dimensions for x3:  3
The size of each dimension for x3:  (3, 4, 5)
The total size of the array x3:  60


In [17]:
print("dtype: ", x1.dtype)
print("itemsize: ", x1.itemsize, "bytes")
print("nbytes: ", x1.nbytes, "bytes")

dtype:  int32
itemsize:  4 bytes
nbytes:  24 bytes


# Array indexing : accessing single elements

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0]

5

In [20]:
x1[4]

7

In [21]:
x1[-1]

9

In [22]:
x1[-2]

7

In [23]:
# In a multidimensional array, access items using a comma-seperated typle of indices

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2[0, 0]

3

In [25]:
x2[2, 0]

1

In [26]:
x2[2, -1]

7

In [27]:
# modifying the values
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# array slicing : accessing subarrays

In [28]:
# [start : stop : step]
# By default start = 0, stop = size of dimension, step =1.

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [30]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [31]:
# middle sub array
x[4:7]

array([4, 5, 6])

In [32]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [33]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [34]:
# when step is -ve, the default for start and stop are swapped
# all elements, reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
# reversed every other from index 5
x[5::-2]

array([5, 3, 1])

In [36]:
# Multidimensional sub arrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [37]:
#  multidimensional slices work in same way, with mutiple slices seperated by commas
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [38]:
# all rows, every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [39]:
# subarray dimensions can even be reversed together
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [40]:
# Accessing array rows and columns

# first column of x2
print(x2[:, 0])

[12  7  1]


In [41]:
# first row of x2

print(x2[0, :])

[12  5  2  4]


In [42]:
# equivalent to x2[0, :]

print(x2[0])

[12  5  2  4]


# subarrays as no-copy views

In [43]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [44]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [45]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [46]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# creating copies of arrays

In [47]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [48]:
# modify this subarray, the original array is not touched

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [49]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of arrays

In [50]:
# the size of the initial array must match the size of the reshaped array

grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# conversion of a one-dimensional array into a two-dimensional row or column matrix.

x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [52]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [53]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [54]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array concatenation and splitting

In [55]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [56]:
# concatenate more than two arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [58]:
# 2d - arrays

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
# For working with arrays of mixed dimensions, use the np.vstack 
#(vertical stack) and np.hstack (horizontal stack) functions

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of arrays

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)


[1 2 3] [99 99] [3 2 1]


In [63]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
