# Load in Numpy

In [1]:
import numpy as np

# Basics

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Get dimension of an array

In [6]:
a.ndim

1

In [7]:
b.ndim

2

# Get shape of an array

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

# Get and modify type

In [10]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [11]:
a.dtype

dtype('int32')

In [12]:
a.itemsize

4

In [13]:
a = np.array([1, 2, 3], dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

In [14]:
a.dtype

dtype('int16')

In [15]:
a.itemsize

2

# Get total size of array

In [16]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [17]:
a.size * a.itemsize

12

In [18]:
a.nbytes

12

# Accessing / changing specific elements, rows, coloumns, etc

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a.shape

(2, 7)

In [21]:
# Get a specific element [r, c]
a[1, 5]

13

In [22]:
a[1, -4]

11

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific coloumn
a[:, 2]

array([ 3, 10])

In [25]:
# [startindex : endindex : stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [26]:
a[0, 1:-2:2]

array([2, 4])

In [27]:
a[0, 1:-1:2]

array([2, 4, 6])

In [28]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [30]:
a[:, 2] = 7
print(a)

[[ 1  2  7  4  5  6  7]
 [ 8  9  7 11 12 20 14]]


In [31]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3d - arrays

In [32]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Get specific element 
a[0, 1, 1]

4

In [35]:
a[: , 1, :]

array([[3, 4],
       [7, 8]])

In [36]:
a[:, 0, :]

array([[1, 2],
       [5, 6]])

In [37]:
a[:, 1, :]

array([[3, 4],
       [7, 8]])

In [38]:
a[:, 1, :] = [[9, 9], [8, 8]]
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [39]:
a[:, 1, :]

array([[9, 9],
       [8, 8]])

# Initializing different types of arrays

In [40]:
# All 0's matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [44]:
# All 1's matrix
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [45]:
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [46]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [47]:
np.full((2, 2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [48]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.08939346, 0.93789157],
       [0.22824397, 0.20123068],
       [0.06042019, 0.95629937],
       [0.89579726, 0.62075338]])

In [52]:
np.random.rand(4, 2, 3)

array([[[0.88096663, 0.1674944 , 0.1578911 ],
        [0.46154713, 0.13761922, 0.34420076]],

       [[0.25043   , 0.32349761, 0.2192364 ],
        [0.61217255, 0.0817134 , 0.78298835]],

       [[0.02224995, 0.00106493, 0.50220311],
        [0.5296824 , 0.63326514, 0.76713041]],

       [[0.66636063, 0.34145236, 0.78384823],
        [0.07961268, 0.78614852, 0.84967646]]])

In [53]:
# To pass shape 
np.random.random_sample(a.shape)

array([[0.78226477, 0.62480898, 0.97757889, 0.39741793, 0.12543141,
        0.34271142, 0.90963543],
       [0.39423653, 0.13712132, 0.80654916, 0.47913444, 0.49384025,
        0.58194965, 0.20001774]])

In [56]:
# Random integer values
np.random.randint(7)

5

In [57]:
np.random.randint(7, size = (3, 3))

array([[4, 4, 4],
       [4, 4, 0],
       [0, 4, 3]])

In [58]:
np.random.randint(4, 7, size = (3, 3))

array([[4, 4, 5],
       [5, 5, 4],
       [4, 6, 5]])

In [59]:
np.random.randint(-4, 8, size = (3, 3))

array([[ 0, -3,  4],
       [ 4, -4,  1],
       [-3,  7,  2]])

In [60]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [64]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [66]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [67]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying arrays

In [69]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [70]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [71]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Calculations

In [72]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [73]:
a + 2

array([3, 4, 5, 6])

In [74]:
a - 2

array([-1,  0,  1,  2])

In [75]:
a * 2

array([2, 4, 6, 8])

In [76]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [77]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [78]:
a = np.array([1, 2, 3, 4])
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [79]:
# Take sin 
a = np.array([1, 2, 3])
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [80]:
# Take cos
a = np.array([1, 2, 3])
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# Linear algebra

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [82]:
# Find the determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [83]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.min(stats)

1

In [85]:
np.max(stats)

6

In [86]:
np.min(stats, axis = 1)

array([1, 4])

In [87]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [88]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [89]:
np.max(stats, axis = 1)

array([3, 6])

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
np.sum(stats, axis = 0)

array([5, 7, 9])

In [93]:
stats = np.array([[1,2,3],[4,5,6]])
np.sum(stats, axis = 1)

array([ 6, 15])

# Reorganizing arrays

In [94]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)


(2, 4)


In [95]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [96]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [97]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [98]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
# Horizontal stack
h1 = np.ones((2,4))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
h2 = np.zeros((2,2))
h2

array([[0., 0.],
       [0., 0.]])

In [102]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [103]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: data.txt not found.